### ISSUE TITLE
Doesn't seem to work with TwoPointFive plugin

### ISSUE THREAD

**Issue by lunarcloud** [Joncom/impact-font-sugar#4]
It seems to hide the "[#FF0000 " and "]", but the color doesn't change.

**Comment by Joncom** [comment]
Mind posting some example code that represents the issue? Have you gotten the plugin to work without TwoPointFive plugin before? Just curious why you mention that plugin specifically.

**Comment by lunarcloud** [comment]
I'll try creating an example project, but [TwoPointFive](https://github.com/phoboslab/TwoPointFive) sorta takes over your project in a way that you can't really remove it. It also modifies font stuff it seems.

**Comment by Joncom** [comment]
Perhaps the simplest test case would be a vanilla copy of the TwoPointFive example, and then simply drop in this plugin.

**Comment by lunarcloud** [comment]
No, I wasn't, I'll test this tonight or tomorrow night and report back.

**Comment by Joncom** [comment]
Any luck?
