### ISSUE TITLE
_getNewFontWidth incorrectly assumes 1px of space in font image

### ISSUE THREAD

**Issue by nathanielhudson** [Joncom/impact-font-sugar#6]
The current implementation of _getNewFontWidth assumes that the font image you pass it has only 1px of space between every letter. However, the base impactjs font actually allows any amount of space between letters. But with Font2, if you pass it a font image with more than 1px of space (see example image) the font displays as cut off since _getNewFontWidth  wont allocate enough space on the new canvas.

![image](https://user-images.githubusercontent.com/2744848/31572206-709e931e-b06e-11e7-81cc-0685a36fc61b.png)

Here's my solution.

        // Returns the new width after accounting for borders.
        _getNewFontWidth: function() {
            var widthFromBorders = this.widthMap.length * (this.borderSize * 2);
            return (widthFromBorders + this.data.width) * ig.system.scale;
        },

I'd create a pull request but I have no idea how to do that!

**Comment by nathanielhudson** [comment]
![techno font](https://user-images.githubusercontent.com/2744848/31576429-8f8efdb8-b0c8-11e7-8ea8-46fbb412a267.png)

Here's an example font that shows the issue.

(PS, thanks for this plugin - I've gotten a ton of use out of it over the years)

**Comment by Joncom** [comment]
@nathanielhudson. Thank you for the bug report, example image, and fix! :)
